// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SafeRouteApi.Data;

#nullable disable

namespace SafeRouteApi.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeRoute.Models.AreasComRiscos", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TipoDeRisco")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("AreaId");

                    b.ToTable("AreasComRiscos");
                });

            modelBuilder.Entity("SafeRoute.Models.RotasSegurancas", b =>
                {
                    b.Property<int>("RotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RotaId"));

                    b.Property<int>("AreaDeRiscoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("AreasComRiscosAreaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Instrucoes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PontosDePassagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("RotaId");

                    b.HasIndex("AreasComRiscosAreaId");

                    b.ToTable("RotasSegurancas");
                });

            modelBuilder.Entity("SafeRoute.Models.RotasSegurancas", b =>
                {
                    b.HasOne("SafeRoute.Models.AreasComRiscos", null)
                        .WithMany("RotasSeguras")
                        .HasForeignKey("AreasComRiscosAreaId");
                });

            modelBuilder.Entity("SafeRoute.Models.AreasComRiscos", b =>
                {
                    b.Navigation("RotasSeguras");
                });
#pragma warning restore 612, 618
        }
    }
}
